INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (1,'Capitulo I - Algumas doenças infecciosas e parasitarias',1,'A00','B99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (2,'Capítulo II - Neoplasias [tumores]',2,'C00','D48');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (3,'Capítulo III  - Doenças do sangue e dos órgãos hematopoéticos e alguns transtornos imunitários',3,'D50','D89');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (4,'Capítulo IV - Doenças endócrinas, nutricionais e metabólicas',4,'E00','E90');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (5,'Capítulo V - Transtornos mentais e comportamentais',5,'F00','F99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (6,'Capítulo VI - Doenças do sistema nervoso',6,'G00','G99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (7,'Capítulo VII - Doenças do olho e anexos',7,'H00','H59');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (8,'Capítulo VIII - Doenças do ouvido e da apófise mastoide',8,'H60','H95');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (9,'Capítulo IX - Doenças do aparelho circulatório',9,'I00','I99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (10,'Capítulo X - Doenças do aparelho respiratório',10,'J00','J99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (11,'Capítulo XI - Doenças do aparelho digestivo',11,'K00','K93');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (12,'Capítulo XII - Doenças da pele e do tecido subcutâneo',12,'L00','L99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (13,'Capítulo XIII - Doenças do sistema osteomuscular e do tecido conjuntivo',13,'M00','M99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (14,'Capítulo XIV - Doenças do aparelho geniturinário',14,'N00','N99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (15,'Capítulo XV - Gravidez, parto e puerpério',15,'O00','O99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (16,'Capítulo XVI - Algumas afecções originadas no período perinatal',16,'P00','P96');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (17,'Capítulo XVII - Malformações congênitas, deformidades e anomalias cromossômicas',17,'Q00','Q99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (18,'Capítulo XVIII - Sintomas, sinais e achados anormais de exames clínicos e de laboratório, não classificados em outra parte',18,'R00','R99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (19,'Capítulo XIX - Lesões, envenenamento e algumas outras consequências de causas externas',19,'S00','T98');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (20,'Capítulo XX - Causas externas de morbidade e de mortalidade',20,'V01','Y98');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (21,'Capítulo XXI - Fatores que influenciam o estado de saúde e o contato com os serviços de saúde',21,'Z00','Z99');
INSERT INTO tbltipodoenca (cdTipoDoenca,dsTipoDoenca, nmCapitulo, catInic, catFinal) Values (22,'Capítulo XXII - Códigos para propósitos especiais',22,'U04','U99');
