-- truncate table ligacao;
truncate table tblaplicamedico;
truncate table tblformacomunica;
truncate table tblclientexdispositivo;
truncate table tblhistdispositivo;
truncate table tblmonitoramento;
truncate table tblpacxdoenca;
truncate table tblacionamento;
truncate table tbltratamento;
truncate table tblocorrencia;
truncate table tblscript;
truncate table tblcontato;
truncate table tblcliente;
truncate table tblcontrato;
truncate table tbldispositivo;
truncate table tblsms;
truncate table tblvendedor;
truncate table tblpacoteservico;
