
public class teste {

    public static void main(String[] args) {

        String a = "frmContrato=frmContrato&frmContrato%3AidTxtSerialize=&frmContrato%3AidTxtCrud=U&frmContrato%3AidTxtIndiceTab=0&frmContrato%3AidTxtIdDispositivo=&frmContrato%3AidTxtIdDoenca=&frmContrato%3AtxtIdHorario=&frmContrato%3AtxtIdTratamento=&frmContrato%3AtxtIdContato=&frmContrato%3AidTabContrato%3AidTxtPedido=257.764.988%2F64&frmContrato%3AidTabContrato%3AidTxtRgContrato=12345678&frmContrato%3AidTabContrato%3AidTxtDataInicioValidade_input=29%2F08%2F2014&frmContrato%3AidTabContrato%3AidTxtDataFinalValidade_input=&frmContrato%3AidTabContrato%3AidTxtDataSuspensao_input=&frmContrato%3AidTabContrato%3AidCmbServico_input=1&frmContrato%3AidTabContrato%3AidTxtRgCliente=4512222&frmContrato%3AidTabContrato%3AidTxtNomeCliente=Rog%C3%A9rio+Luciano+dos+Santos&frmContrato%3AidTabContrato%3AidTxtEnderecoCliente=Alameda+Jo%C3%A3o+Galego%2C+304&frmContrato%3AidTabContrato%3AidTxtBairroCliente=Santa+Maria&frmContrato%3AidTabContrato%3AidTxtCidadeCliente=S%C3%A3o+Caetano+do+Sul&frmContrato%3AidTabContrato%3AidComboUfCliente_input=SP&frmContrato%3AidTabContrato%3AidTxtCepCliente=09560-340&frmContrato%3AidTabContrato%3AidCboSexoCliente_input=1&frmContrato%3AidTabContrato%3AidTxtDataNascimentoCliente_input=06%2F06%2F1977&frmContrato%3AidTabContrato%3Aj_idt61=&frmContrato%3AidTabContrato%3AidTxtPlanoSaude=&frmContrato%3AidTabContrato%3Aj_idt297=&frmContrato%3AidTabContrato%3AidTxtFiltroDispositivo=&frmContrato%3AidTabContrato%3AidTxtFiltroCentral=&frmContrato%3AidTabContrato%3AidTxtHorasimobilidade=5&frmContrato%3AidTabContrato%3AidTxtFiltroDoencas=&frmContrato%3AidTabContrato%3AidTxtNomeTratamento=&frmContrato%3AidTabContrato%3Aj_idt321_input=&frmContrato%3AidTabContrato%3AcmbPeridiocidade_input=1&frmContrato%3AidTabContrato%3AidTxtDescricaoTratamento=&frmContrato%3AidTabContrato%3AidTxtNomeContato=&frmContrato%3AidTabContrato%3Aj_idt337_input=0&frmContrato%3AidTabContrato%3AidTxtEnderecoContato=&frmContrato%3AidTabContrato%3AidTxtBairroContato=&frmContrato%3AidTabContrato%3AidTxtCidadeContato=&frmContrato%3AidTabContrato%3Aj_idt343_input=SP&frmContrato%3AidTabContrato%3AidTxtCepContato=&frmContrato%3AidTabContrato%3AidTxtDataNascimentoContato_input=&frmContrato%3AidTabContrato%3AidSpinSequenciaChamada_input=&frmContrato%3AidTabContrato_activeIndex=0&frmContrato%3AtxtIdFormaContatoCliente=&frmContrato%3AidCmbTipoFormaContatoCliente_input=1&frmContrato%3AidTxtFormaContatoClienteTelefone=&frmContrato%3AidTxtFormaContatoClienteEmail=&frmContrato%3AidTxtHorarioTratamento=&frmContrato%3AtxtIdFormaContato=&frmContrato%3AidCmbTipoFormaContato_input=1&frmContrato%3AidTxtFormaContatoTelefone=&frmContrato%3AidTxtFormaContatoEmail=&javax.faces.ViewState=6636402647530563833%3A6994359964707918513";
        String b =  "frmContrato=frmContrato&frmContrato%3AidTxtSerialize=&frmContrato%3AidTxtCrud=U&frmContrato%3AidTxtIndiceTab=0&frmContrato%3AidTxtIdDispositivo=&frmContrato%3AidTxtIdDoenca=&frmContrato%3AtxtIdHorario=&frmContrato%3AtxtIdTratamento=&frmContrato%3AtxtIdContato=&frmContrato%3AidTabContrato%3AidTxtPedido=257.764.988%2F64&frmContrato%3AidTabContrato%3AidTxtRgContrato=12345678&frmContrato%3AidTabContrato%3AidTxtDataInicioValidade_input=29%2F08%2F2014&frmContrato%3AidTabContrato%3AidTxtDataFinalValidade_input=&frmContrato%3AidTabContrato%3AidTxtDataSuspensao_input=&frmContrato%3AidTabContrato%3AidCmbServico_input=1&frmContrato%3AidTabContrato%3AidTxtRgCliente=4512222&frmContrato%3AidTabContrato%3AidTxtNomeCliente=Rog%C3%A9rio+Luciano+dos+Santos&frmContrato%3AidTabContrato%3AidTxtEnderecoCliente=Alameda+Jo%C3%A3o+Galego%2C+304&frmContrato%3AidTabContrato%3AidTxtBairroCliente=Santa+Maria&frmContrato%3AidTabContrato%3AidTxtCidadeCliente=S%C3%A3o+Caetano+do+Sul&frmContrato%3AidTabContrato%3AidComboUfCliente_input=SP&frmContrato%3AidTabContrato%3AidTxtCepCliente=09560-340&frmContrato%3AidTabContrato%3AidCboSexoCliente_input=1&frmContrato%3AidTabContrato%3AidTxtDataNascimentoCliente_input=06%2F06%2F1977&frmContrato%3AidTabContrato%3Aj_idt61=&frmContrato%3AidTabContrato%3AidTxtPlanoSaude=&frmContrato%3AidTabContrato%3Aj_idt297=&frmContrato%3AidTabContrato%3AidTxtFiltroDispositivo=&frmContrato%3AidTabContrato%3AidTxtFiltroCentral=&frmContrato%3AidTabContrato%3AidTxtHorasimobilidade=5&frmContrato%3AidTabContrato%3AidTxtFiltroDoencas=&frmContrato%3AidTabContrato%3AidTxtNomeTratamento=&frmContrato%3AidTabContrato%3Aj_idt321_input=&frmContrato%3AidTabContrato%3AcmbPeridiocidade_input=1&frmContrato%3AidTabContrato%3AidTxtDescricaoTratamento=&frmContrato%3AidTabContrato%3AidTxtNomeContato=&frmContrato%3AidTabContrato%3Aj_idt337_input=0&frmContrato%3AidTabContrato%3AidTxtEnderecoContato=&frmContrato%3AidTabContrato%3AidTxtBairroContato=&frmContrato%3AidTabContrato%3AidTxtCidadeContato=&frmContrato%3AidTabContrato%3Aj_idt343_input=SP&frmContrato%3AidTabContrato%3AidTxtCepContato=&frmContrato%3AidTabContrato%3AidTxtDataNascimentoContato_input=&frmContrato%3AidTabContrato%3AidSpinSequenciaChamada_input=&frmContrato%3AidTabContrato_activeIndex=0&frmContrato%3AtxtIdFormaContatoCliente=&frmContrato%3AidCmbTipoFormaContatoCliente_input=1&frmContrato%3AidTxtFormaContatoClienteTelefone=&frmContrato%3AidTxtFormaContatoClienteEmail=&frmContrato%3AidTxtHorarioTratamento=&frmContrato%3AtxtIdFormaContato=&frmContrato%3AidCmbTipoFormaContato_input=1&frmContrato%3AidTxtFormaContatoTelefone=&frmContrato%3AidTxtFormaContatoEmail=&javax.faces.ViewState=6636402647530563833%3A6994359964707918513";
        
        if (a.equals(b)) {
            System.out.println("OK");
        }
        
        

    }

}
